from django.conf.urls import patterns, url

from .views import (StationListView, MeterListView, MeterDetailView,
        LogListView, MeterInfoListView, ModeListView, CreateModeView,
        CreateMeterInfoView, CreateStationView, MeterInfoDetailView,
                    CreateMeterView, UpdateMeterInfoView, ModeDetailView,
                    UpdateModeView, TowerListView, TowerDetailView,
                    WellListView)


urlpatterns = patterns('',
        url(r'^stations/$',
            StationListView.as_view(), name='list_stations'),
        url(r'^stations/(?P<pk>\d+)/meters/$',
            MeterListView.as_view(), name='station_meters_list'),
        url(r'^stations/create/$',
            CreateStationView.as_view(), name='create_station'),
        url(r'^meter/(?P<pk>\d+)/$',
            MeterDetailView.as_view(), name='meter_detail'),
        url(r'^meter/(?P<pk>\d+)/create/$',
            CreateMeterView.as_view(), name='create_meter'),
        url(r'^logs/$',
            LogListView.as_view(), name='list_logs'),
        url(r'^meter_infos/$',
            MeterInfoListView.as_view(), name='list_meter_infos'),
        url(r'^meter_infos/(?P<pk>\d+)/$',
            MeterInfoDetailView.as_view(), name='meter_info_detail'),
        url(r'^meter_infos/create/$',
            CreateMeterInfoView.as_view(), name='create_meter_info'),
        url(r'^meter_infos/(?P<pk>\d+)/update/$',
            UpdateMeterInfoView.as_view(), name='update_meter_info'),
        url(r'^modes/$',
            ModeListView.as_view(), name='list_modes'),
        url(r'^mode/(?P<pk>\w+)/$',
            ModeDetailView.as_view(), name='mode_detail'),
        url(r'^mode/(?P<pk>\w+)/update/$',
            UpdateModeView.as_view(), name='update_mode'),
        url(r'^modes/create/$',
            CreateModeView.as_view(), name='create_mode'),
        url(r'^towers/$',
            TowerListView.as_view(), name='tower_list'),
        url(r'^towers/(?P<pk>\d+)/$',
            TowerDetailView.as_view(), name='tower_detail'),
        url(r'^wells/$',
            WellListView.as_view(), name='well_list'),
        url(r'^accounts/login/$',
            'django.contrib.auth.views.login', name='login'),
        url(r'^accounts/logout/$',
            'django.contrib.auth.views.logout_then_login', name='logout'),
)
